### ISSUE TITLE
Confused about the time complexity？

### ISSUE THREAD

**Issue by dyy401453043** [facebookresearch/SEAL#16]
Thanks for your great work! 
In your paper, you say "The FM-index can be used to count the frequency of any sequence of tokens n in O(|n|log|V|)".
But, according to the wikipedia's explanation, the count operation in FM-index can be done in O(|n|) time for a pattern with n item. I don't understand why there is a log|V| in your conclusion.
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/39038834/186405637-776ad701-88cc-4d5f-be32-13f42b308ac8.png">
Similarly, I don't understand why "the list of possible token successors can be obtained in O(|V|log|V|)", why the time is relevant to V, can you give a little explanation? I would really appreciate it!

**Comment by mbevila** [comment]
Hi,

The last column of the rotation matrix of the FM-index is implemented as a [Wavelet Tree](https://en.m.wikipedia.org/wiki/Wavelet_Tree). To search in the FM-index you perform 2n WT rank operations to count how many times a given symbol occurs in a certain range of rows. Each rank call is O(log |V|), and gets called twice for each element of the pattern, once passing the initial index of the range and once passing the final one. I think it corresponds to `Occ` in the Wikipedia page you have mentioned.

Getting all successors given a range of rows in the  FM-index has that complexity because you call the WT rank operation 2|V|, i.e., twice for each symbol, so that you know how many times each occurs in the interval.
